name: task_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"   # Compatível com Dart 3.9.2 do Flutter 3.35

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.3
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  sensors_plus: ^4.0.2
  vibration: ^1.8.4
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # shared_preferences (adicione se for usar persistência simples)
  # shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
